src/Entity/OrderProduct.php
<?php

namespace App\Entity;

use App\Repository\OrderProductRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderProductRepository::class)
 */
class OrderProduct
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, fetch="EAGER")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Product;

    /**
     * @ORM\Column(type="integer")
     */
    #[Assert\NotBlank]
    #[Assert\GreaterThanOrEqual(1)]
    private $Quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $orderObj;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $productName;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $priceProduct;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getOrderObj(): ?Order
    {
        return $this->orderObj;
    }

    public function setOrderObj(?Order $orderObj): self
    {
        $this->orderObj = $orderObj;

        return $this;
    }


    public function equals(OrderProduct $obj)
    {
        return $this->getProduct()->getId() === $obj->getProduct()->getId();
    }

    public function getSum(): ?float
    {
        if($this->Quantity <= 0 )
            return $this->getPriceProduct();

        return $this->getQuantity() * $this->getPriceProduct();
    }

    public function getProductName(): ?string
    {
        return $this->productName;
    }

    public function setProductName(string $productName): self
    {
        $this->productName = $productName;

        return $this;
    }

    public function getPriceProduct(): ?string
    {
        return $this->priceProduct;
    }

    public function setPriceProduct(string $priceProduct): self
    {
        $this->priceProduct = $priceProduct;

        return $this;
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Order;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use App\Event\RemoveFromCartSubscriber;
use App\Event\CartRemoveAllSubscriber;

// Cart form 
// Collection of cart items
class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('items', CollectionType::class,[
                'entry_type' => CartItemType::class
            ])
            ->add('change', SubmitType::class)
            ->add('clear',SubmitType::class)
        ;

        $builder->addEventSubscriber(new RemoveFromCartSubscriber());
        $builder->addEventSubscriber(new CartRemoveAllSubscriber());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Service\CartManagment;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\CartType;
use Symfony\Component\HttpFoundation\Request;

class CartController extends AbstractController
{
    // Cart page
    #[Route('/cart', name: 'cart')]
    public function index(Request $request,CartManagment $cartMngmt): Response
    {
        $this->denyAccessUnlessGranted('ROLE_CLIENT');
        $cart = $cartMngmt->getCart();
        $form = $this->createForm(CartType::class, $cart);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $cartMngmt->saveCart($cart);

            return $this->redirectToRoute('cart');
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}E-Shop  - Cart {% endblock %}

{% block body %}

<style>
.image-wrapper {max-width: 200px; max-height:200px;}
</style>

<h1 class='text-center display-4'>Your cart</h1>
<hr class='w-100' />
 {{ form_start(form) }}
 {% if cart.items.count > 0 %}
    <div class='mb-3'>
        {{ form_widget(form.change, {'attr': {'class': 'btn btn-info'}}) }}
        {{ form_widget(form.clear, {'attr': {'class': 'btn btn-warning'}}) }}
    </div>
 {% endif %}
 
<div class='row'>
{{ form_row(form._token) }}
    <div class='col-sm-12 table-responsive text-center'>
        {% if cart.items.count > 0 %}
        <table class='table table-hover'>
            <thead class='thead-dark'>
                <th>#</th>
                <th>Picture</th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Actions</th>
            </thead>
            <tbody>
            {% for item in form.items %}
                <tr>
                <td class='align-middle'>{{loop.index}}</td>
                <td class='align-middle text-center'>
                {% if item.vars.data.product is not null %}
                    <a href='{{  path('product', {id: item.vars.data.product.id, name: item.vars.data.product.name}) }}'>
                        {% if item.vars.data.product.imageFileName is empty %}
                            <img src="{{ asset('img/products/no-image.png')}}" class="image-wrapper" >
                        {% else %}
                            <img src="{{ asset('img/products/' ~ item.vars.data.product.imageFileName)}}" class="image-wrapper" >
                        {% endif %}
                    </a>
                {% else %}
                <img src="{{ asset('img/products/no-image.png')}}" class="image-wrapper" >
                {% endif %}
                </td>
                <td class='align-middle'>
                {% if item.vars.data.product is not null %}
                <a href='{{  path('product', {id: item.vars.data.product.id, name: item.vars.data.product.name }) }}' class='text-decoration-none'>{{ item.vars.data.productName }}</a>
                {% else %}
                {{ item.vars.data.productName }}
                {% endif %}
                </td>
                <td class='align-middle'>{{ item.vars.data.priceProduct }}$</td>
                <td class='align-middle'>
                    <div class='w-25 d-block mx-auto'>
                    {{ form_widget(item.quantity) }}
                    </div>
                </td>
                <td class='align-middle'>{{ item.vars.data.Sum  }}$</td>
                <td class='align-middle'>
                    {{ form_widget(item.action, {'label': 'Remove', 'attr':{'class':'btn btn-danger'}}) }}
                </td>
                </tr>
            {% endfor %}
                <tr>
                <td class='align-middle'></td>
                <td class='align-middle text-center'></td>
                <td class='align-middle'></td>
                <td class='align-middle'></td>
                <td class='align-middle'>Total</td>
                <td class='align-middle'>{{ cart.OrderSum  }}$</td>
                <td class='align-middle'></td>
                </tr>
            </tbody>
        </table>
        <a href='{{ path('create_order', {id: cart.id})}}' class='btn btn-secondary'>New order</a>
        {% else %}
            <h3 class='text-danger text-center mt-4 display-4'>Empty cart</h3>
        {% endif %}
    </div>


</div>
{% endblock %}